name: Publish documentation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  publish:
    runs-on: ubuntu-latest 

    permissions:
      contents: write  # For creating releases
      id-token: write  # For trusted publishing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Installing uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: '3.12'
    
    - name: Install build dependencies  # ADD THIS STEP
      run: uv sync --all-extras       

    - name: Build HTML
      run: | 
        cd source/
        uv run make html
    
    - name: Deploy documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./source/_build/html
